#pragma once
#include "vec.h"
#include "mat.h"
#include "qtrn.h"

#include "Shader.h"
#include "ShaderManager.h"
#include "Camera.h"
#include "OrthogonalCamera.h"
#include "PerspectiveCamera.h"
#include "Mesh.h"
#include "MeshManager.h"
#include "SceneNode.h"
#include "SceneGraph.h"
#include "SceneGraphManager.h"
